version: '3'

services:

    hello:
        image: hello
        ports:
            - "8000:8000"

    prometheus:
        image: prometheus
        ports:
            - "9090:9090"

    grafana:
        image: grafana/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        ports:
            - "3000:3000"
