{
 "title": "Hello",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "hello_version_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum without (name, pid) (rate(hello_request_count_total[5m]))"
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(hello_request_count_total[5m]))"
    }
   ]
  },
  {
   "title": "Distribution over time with total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pid) (rate(hello_request_count_total[5m]))"
    },
    {
     "expr": "sum without (pid, name) (rate(hello_request_count_total[5m]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"hello\"}[5m])"
    },
    { "expr": "process" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"hello\"} / 1024"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum without (pid) (increase(hello_latency_seconds_bucket[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency CDF",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum without (le) (rate(hello_latency_seconds_bucket[5m]))"
    }
   ]
  }
 ]
}